language: node_js
node_js:
  - 12.16
script: true
deploy:
  provider: heroku
  api_key:
    secure: "CpgKlvHD1vVj0QqBjnKDA/4Bw1nQDwpPlrJWrgWc3HoW/2aBXNLazFuTqL8PNHAyUGMRa+4kfUsOdh74vanCCpxN6BXT1uBdPEUXD0INuZeXM99ZyzoMMyeU3e2tc2ivSTN9h8M9dZho4UnhnAKIykAcMRkPHCoKWXCfKdcHWo7UK1GA92OSsLaVpIveSGY47/zFRc31PriKKbOtadm+GX4Rdm90cSncwPuYBeeWICAN8RL4rt8r+F44jX3sg/z3all78cQWPGlSdAOD/ShOD23XzVEt42Mj6PLz7tuTs5FMimtj3Z8V2P0ZIYJ7Brz63/6Ek9tT1MdrRbQpwCWMlKvJrgF5l
  DnYszfV+1NaGlP1mqrznjTrHmHwnGTBCUi9+bGz9T244rae95IEkamuwX9OvJsh78w7xSOw5bH4ZChL/9ufprjcyDpA4cmLHjSF1jZxj4z3HjPPJkFyJjyYOdOz92BoIni3UZw9+jsl3vLADkBovrboe4ulWAbgFigmjNNEDgOsagAWJqCLVre2/an2B4tU4PVrUoofKZPiIYit8L0oboey7U8YBp5IM8e1R24TiXmMSyQiu6IzXnMOW22JYzJbe7s1eJszYFI6rWGi0tS14+XBS5x/4tWqOYEwZO23Cu34HrOtTIDTP/2CVJMmw8weaiaTqycrbjfOeNc=
app: road-to-device-lab
on:
  repo: tnanhekhan/browser-technologies-1920
  branch: staging
branches:
  only:
    - staging