language: node_js
node_js:
  - 12.16
script: true
deploy:
  provider: heroku
  api_key:
    secure: g5nKw62SxTD2I8qqRRTKnZdKTR5UYhYhSkBQMonVg/FZQ8AOgPRrDtpuHusuOMaJOtmqW+r6CbnspRjI8h3KPyyqXbvLolB9aBhhd0ltqbpKalmqLgocJLD/i/RODKm+yDXsWxtY6GcM+FPQtwPja9TY/goVtCXADe3x5I2ecLI/GpqSI5V+28/iiQ2XNs1l6p8RYpVTFtQsZrkv8SIIkx+3kQC96cUFgczZPVsJEtPK5f3MofE8ovt1KSFePnK1qAlITBaIsOO7VU3R4pr9FWeP9WPvREK5qUh58fZG6TjIWpBcIwjQNi7oBKpGsVkPGjK4HM7cZj66Hg8l39wc4yRjFscvSN5zDPhb0CWXWINZRe5mIZv2uD3wPSpnXLgoEG//oYY3U3lSymmKz40mY2yhfVbLfQT/ytC056wFCWvTOWy16Ftn1tDy4bogfMUIZnUFleLFVNkKWpuB5F0dqkBBiA92o0cIUx4Nqpd2YZiu8FpFakP9fHBpZqchYDJqa7mqf7QeUvZpJ30pKM+qI0Q+hTUH/i7jFGMxSTh2qYTGB4im8QVjbmiJeXhXPc8hvCE7nRXqMra5X+g59c8rVfGmbSzM70vY8wBh+ZQ/K4PqCHfCF2BFvieNaSetJ9ytvPLBYU/eWOAeg2wWBzFPhAoMGyMPq2ttnF5aCyZvmKU=
  app: road-to-device-lab
  on:
    repo: tnanhekhan/browser-technologies-1920
    branch: staging
branches:
  only:
    - staging
